const pokemonsBySearchConstant = {
    POKEMONS_SEARCH: "POKEMONS_SEARCH",
    POKEMONS_SEARCH_FETCHING: "POKEMONS_SEARCH_FETCHING",
    POKEMONS_SEARCH_ERROR: "POKEMONS_SEARCH_ERROR",
}

export default pokemonsBySearchConstant;